### ISSUE TITLE
RuntimeError: deque mutated during iteration

### ISSUE THREAD

**Issue by gaskolar** [vicoslab/vicos_ros#3]
Na vsake toliko se sprozi naslendnja izjema.

[ERROR] [WallTime: 1466698786.568500] bad callback: <bound method DetectionMapper.detection_callback of <__main__.DetectionMapper instance at 0x7fea8d9258c0>>
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/topics.py", line 720, in _invoke_callback
    cb(msg)
  File "/home/team_beta/ROS/src/vicos_ros/depth/localizer/src/mapper", line 29, in detection_callback
    for ci in self.camera_infos:
RuntimeError: deque mutated during iteration

**Comment by lukacu** [comment]
Yes, it is a problem with synchronization, at least one other group reported this. A mutex could solve this, but I would like to stress out that the mapper was always intended more as an example and was never designed to be used in practice.
